# Generated by Django 2.0.5 on 2018-06-21 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [('orders', '0002_auto_20180524_2158'), ('orders', '0003_auto_20180530_1117'),
                ('orders', '0004_auto_20180621_2207')]

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='orders.Order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='customerOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='orders.CustomerOrder'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders',
                                    to='customers.Customer', verbose_name='Покупатель'),
        ),
    ]
