# Generated by Django 2.0.5 on 2018-05-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'get_latest_by': 'date'},
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='orders.Order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='customerOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='orders.CustomerOrder'),
        ),
    ]
