# Generated by Django 2.0.5 on 2018-06-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0003_add_sorting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='confirmed_amount',
        ),
        migrations.AddField(
            model_name='productorder',
            name='_confirmed_amount',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Подтвержденное количество'),
        ),
    ]
