# Generated by Django 2.0.5 on 2018-06-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_sorting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='confirmed_amount',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Подтвержденное количество'),
        ),
    ]
