# Generated by Django 2.0.5 on 2019-01-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_make_confirmed_amount_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='amount',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Количество'),
        ),
    ]
